<?php

declare(strict_types=1);

namespace App\Infrastructure\Http\Exception;

enum ErrorCodesEnum: int
{
    case CONTENT_NEGOTIATION_NOT_ACCEPTABLE = 1000;
    case CONTENT_NEGOTIATION_UNSUPPORTED_MEDIA_TYPE = 1001;
    case ENDPOINT_DOES_NOT_SUPPORT_THE_INCLUDE_PARAMETER = 1010;
    case ENDPOINT_DOES_NOT_SUPPORT_THE_INCLUSION_OF_THIS_RESOURCE = 1011;
    case INCORRECT_INCLUSION_FIELD = 1012;
    case VALIDATION_EXCEPTION = 1100;
    case RESOURCE_NOT_FOUND = 1101;
    case INTERNAL_SERVER_ERROR = 1200;

    case SLIM_HTTP_EXCEPTION = 2000;
}
