version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: ishual_books
      POSTGRES_USER: ishual_books
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  db_test:
    image: postgres
    environment:
      POSTGRES_DB: ishual_books_test
      POSTGRES_USER: ishual_books
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    profiles:
      - donotstart